### ISSUE TITLE
mml2tex

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qformat_mapleta#1]
Can we look over all the CASText fields and convert
`<!--?mml2tex R^{3}?-->`
to
`\( R^{3} \)`
Something like this?
`preg_match("/<!--\?mml2tex(.*)-->/", $input_line, $output_array);`

**Comment by georgekinnear** [comment]
This has been partially addressed, for pure multiple choice questions with no algorithmic variables.

The only other issues I could see were from display equations where the tex code was split over multiple lines - the existing regular expression does not seem to pick these up. However the number of instances of this is small, so I've not tried to fix it.
